### ISSUE TITLE
Footer is always "pushed" down below viewport

### ISSUE THREAD

**Issue by megoth** [inrupt/solid-style-guide#48]
The element between header and footer is always 100% it seems. I would change this to

```
height: 100%;
height: calc(100% - 120px);
```

To make it part of the viewport for browser that supports the calc-function.

**Comment by james-martin-jd** [comment]
We've updated the footer so it's now a "pushed" footer. If the content is <100% of the screen it is on the bottom of the screen, otherwise it is pushed to the bottom of the content.
